# Stubs for modulators.modulator_base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Modulator:
    @staticmethod
    def generate_timearray(dt: Any, sample_count: Any): ...
    def modulate(self, data: Any) -> None: ...
    def demodulate(self, time_array: Any, datastream: Any) -> None: ...
