# Stubs for modulators.modulator_base (Python 3)

from typing import Any

class Modulator:
    @staticmethod
    def generate_timearray(dt: float, sample_count: int): ...
    def modulate(self, data: Any) -> None: ...
    def demodulate(self, time_array: Any, datastream: Any) -> None: ...
