# Stubs for modulators.modulator_utils (Python 3)

from typing import Any, Sequence, Tuple

from numpy import ndarray

class ModulationIntegrityWarning(UserWarning): ...

def generate_timearray(fs: float, sample_count: int) -> ndarray: ...
def samples_per_symbol(fs: float, baud: float) -> float: ...
def previous_resample_interpolate(timeseq: ndarray, baud: float, sequence: Sequence[float]) -> ndarray: ...
def average_interval_data(data: Sequence[float], begin: float, end: float) -> float: ...

def gaussian_window(fs: float, sigma_dt: float) -> ndarray: ...
def fred_harris_fir_tap_count(fs: float, transition_width: float, db_attenuation: float) -> int: ...
def lowpass_fir_filter(fs: float, cutoff_low: float, cutoff_high: float, attenuation: float = ...) -> ndarray: ...

def linearize_fir(filter: Any) -> None: ...

def goertzel_iir(freq: float, fs: float) \
    -> Tuple[Sequence[complex],Sequence[complex]]: ...