from .modulator_base import BaseModulator
from typing import Sequence, Dict, Tuple

from numpy import ndarray

class QAMModulator(BaseModulator):
    fs: float = ...
    constellation_list: Dict[int, complex] = ...
    carrier_freq: float = ...
    baud: float = ...
    def __init__(self, fs: float, carrier: float,
            constellation_list: Sequence[complex], baud: float) -> None: ...
    def modulate(self, datastream: Sequence[int]) -> ndarray: ...
    def demodulate(self, modulated_data: ndarray) -> Sequence[int]: ...
