# Stubs for modulators.modulator_ask (Python 3)

from .modulator_base import Modulator
from typing import Any, List, Dict, Tuple

class ASKModulator(Modulator):
    fs: float = ...
    amp_list: Dict[int, float] = ...
    baud: float = ...
    def __init__(self, fs: float, carrier: float,
            amp_list: List[float], baud: float) -> None: ...
    def modulate(self, data: Any) -> Tuple[Any, Any]: ...
    def demodulate(self, time_array: Any, datastream: Any) -> None: ...
