from .modulator_base import BaseModulator
from typing import Sequence, Dict, Tuple

from numpy import ndarray

class PSKModulator(BaseModulator):
    fs: float = ...
    phase_list: Dict[int, float] = ...
    carrier_freq: float = ...
    baud: float = ...
    def __init__(self, fs: float, carrier: float, amplitude: float,
            phase_list: Sequence[float], baud: float) -> None: ...
    def modulate(self, datastream: Sequence[int]) -> ndarray: ...
    def demodulate(self, modulated_data: ndarray) -> Sequence[int]: ...
