from .modulator_base import Modulator
from typing import Sequence, Dict, Tuple

from numpy import ndarray

class FSKModulator(Modulator):
    fs: float = ...
    freq_list: Dict[int, float] = ...
    amplitude: float = ...
    baud: float = ...
    def __init__(self, fs: float, amplitude: float,
            freq_list: Sequence[float], baud: float) -> None: ...
    def modulate(self, datastream: Sequence[int]) -> ndarray: ...
    def demodulate(self, modulated_data: ndarray) -> Sequence[int]: ...
