language: python

notifications:
  email: false

# Need this for now to build SciPy for Python 3.8
addons:
  apt:
    packages:
    - liblapack-dev

#TODO: properly troubleshoot mypy permission errors
matrix:
  include:
    - python: '3.8'
      os: linux
    - python: '3.7'
      env: MYPY=true
      os: linux
    - python: '3.6'
      os: linux
    - python: '3.5'
      os: linux

cache: pip

install:
  - pip install pipenv
  - rm Pipfile.lock # Re-lock dependencies
  - pipenv lock -r > requirements.txt
  - cat requirements.txt
  - pip install -r requirements.txt
  - pip install pytest coverage
  - if [ $MYPY = true ]; then pip install mypy; pip install -e git+https://github.com/numpy/numpy-stubs.git; fi

script:
  - sh ./run_tests_coverage.sh
  - if [ $MYPY = true ]; then sh ./run_mypy.sh; fi

after_script:
  - wget -O codecov_upload "https://codecov.io/bash"
  - bash codecov_upload
