language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pipenv lock -d >> requirements.txt
  - pip install -r requirements.txt

script:
  - ./run_test_coverage.sh
