language: python

notifications:
  email: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - rm Pipfile.lock # Re-lock dependencies
  - pipenv lock -r > requirements.txt
  - cat requirements.txt
  - pip install -r requirements.txt
  - pip install pytest coverage
  - echo $TRAVIS_PYTHON_VERSION

script:
  - sh ./run_tests_coverage.sh
