# Stubs for encoders.ecc.hamming_7_4 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..bitstream import readable_bytearr, read_bitstream, write_bitstream
from typing import Any

def hamming_encode_7_4(bitstream: readable_bytearr) -> bytes: ...
def hamming_decode_7_4(bitstream: readable_bytearr) -> bytes: ...
